# yaml file to orquestrate the services of the system:
# DB - API - Simulation

version: "3.9"

services:

  db:
    image: postgres:14
    container_name: elevator_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: elevator_sim
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: elevator_api
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/elevator_sim
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app

  simulator:
    build:
      context: .
      dockerfile: Dockerfile.sim
    container_name: elevator_simulator
    restart: "no"  # does not run continously
    depends_on:
      - api
    environment:
      API_BASE_URL: http://api:8000
    command: ["python", "runner.py"]
    volumes:
      - ./simulation_runner:/sim

volumes:
  postgres_data:
